### ISSUE TITLE
Research electron build/packaging

### ISSUE THREAD

**Issue by e-l-i-s-e** [ez-ql/ez-ql-electron-react#32]

**Comment by neckenth** [comment]
build is complete, and we have binaries for the splash page!

resources used: 

process:
https://doc.xuwenliang.com/docs/electron/1276
https://medium.com/how-to-electron/a-complete-guide-to-packaging-your-electron-app-1bdc717d739f
http://kazuar.github.io/markdown-app/

debugging:
https://github.com/electron-userland/electron-builder/issues/2955
https://github.com/electron-userland/electron-builder/issues/2404
https://www.christianengvall.se/electron-app-icons/

tool to convert icons: https://iconverticons.com/online/

maybe we could have used this earlier....https://github.com/crilleengvall/electron-tutorial-app

Will submit a PR for the added files in addition to the changes with heroku postgres env vars.
